### ISSUE TITLE
Probably user error

### ISSUE THREAD

**Issue by jadedtakesthiscereal** [maximedrn/opensea-collection-scraper#1]
what did i mess up already
![scrape](https://user-images.githubusercontent.com/102177219/161870278-a7d0a676-da3d-4870-8ec4-90c9e7f4ae48.png)

using gumroad copy, now python 3.9.12 (3.11 fails), win 10,

**Comment by jadedtakesthiscereal** [comment]
..well now I made it worse lol.   was using python 3.10  upgraded to 3.11 .. now I fail to build 
 note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for numpy
manually installing it is pandas that errors same as above..

 do not know if related but my system also says missing torch and unable to find version even when doing pip install torch torchvision torchaudio  .. which makes my requirements txt pip install for the uploader fail

**Comment by jadedtakesthiscereal** [comment]
this is how the error starts when trying pandas manual pip... goes for pages ends with the note in post above
![scrape2](https://user-images.githubusercontent.com/102177219/161885616-971077d7-0a59-43c2-85ea-78865e1be0c8.png)

**Comment by jadedtakesthiscereal** [comment]
.. solved had to use npm install minimist and then it took about 2 minutes or less to generate the file.  I was hoping it would pull the name too (so i could verify all posted correctly in original uploading, or remove sold items) but the file it does give will be very useful for relisting.. thanks Maxime.. if I am using this wrong and I can also pull name please let me know.. closing this

**Comment by maximedrn** [comment]
I didn't try with 3.11, I think some modules don't work with this new version of Python.

The Minimist package is present in the `packages.json` file, it's strange that the installation didn't work the first time with `npm install` :s
